In [35]:
import pandas as pd
story_generate = __import__('01_story_generate')

subject = 'UTS02'
rows = story_generate.get_rows_voxels(subject=subject)
rows['top_ngrams_module_correct'] = rows['top_ngrams_module_correct'].apply(lambda x: x[:5])

with pd.option_context('display.max_colwidth', None):
    display(rows[['expl', 'roi_func', 'top_ngrams_module_correct']].style.hide(axis='index'))

len(voxel_nums) 17 nunique 17